#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2017, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/kvmrc
source $(dirname $0)/../../scripts_common.sh

DOMAIN="$1"
SNAP_ID="$2"


data=`virsh --connect $LIBVIRT_URI snapshot-create-as $DOMAIN`

if [ "$?" = "0" ]; then
    echo "$data" | awk '{print $3}'

    VM_ID=`echo "$DOMAIN" | sed 's/one-//'`
    SNAP_SAVE_DIR="/var/lib/one/datastores/0/$VM_ID/snapxml_save"
    snapshot_name=`echo "$data" | awk '{print $3}'`
    if [ ! -d "$SNAP_SAVE_DIR" ];then
        mkdir $SNAP_SAVE_DIR
        chmod 775 $SNAP_SAVE_DIR
    fi
    virsh --connect $LIBVIRT_URI snapshot-dumpxml $DOMAIN $snapshot_name --security-info\
    > ${SNAP_SAVE_DIR}/${snapshot_name}.xml
    echo "Save snapshot ${snapshot_name}.xml for domain $DOMAIN"

else
    error_message "Could not create snapshot $NAME for domain $DOMAIN."
    exit -1
fi

exit 0
