#!/bin/bash
source $(dirname $0)/kvmrc
source $(dirname $0)/../../scripts_common.sh

source_file=$1
dom_shell=$(dirname $0)/get_dom_value.py

# get info from xml deployment file
domain_name=$(python $dom_shell -n $source_file)
VM_ID=`echo $domain_name | sed 's/one-//'`
VM_UUID=`virsh --connect $LIBVIRT_URI domuuid $domain_name`
snapshot_save_dir="/var/lib/one/datastores/0/$VM_ID/snapxml_save"


if [ -d "$snapshot_save_dir" ] && [ "`ls -A $snapshot_save_dir`" != "" ];then
    snap_list=($(ls $snapshot_save_dir |sort))
    for snapxml in ${snap_list[@]}
    do
        xml_path=${snapshot_save_dir}/${snapxml}
        sed -i "s/<uuid>.*<\/uuid>/<uuid>$VM_UUID<\/uuid>/" ${xml_path}
        exec_and_log \
            "virsh --connect $LIBVIRT_URI snapshot-create $domain_name ${xml_path} --redefine" \
            "Could not redefine snapshot ${snapxml} for domain $source_file."
        if [ "$?" = 0 ];then
            echo "Snapshot ${snapxml} for domain $domain_name redefine"
        fi

    done
else
    echo "No snapshot for domain $domain_name"
    exit 121
fi

exit 0